theme: jekyll-theme-minimal
title: Sub Genie
description: Sub Genie is specifically designed to provide real-time translation of Crunchyroll subtitles into various Indian languages, enhancing accessibility for non-English speaking viewers.
